### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by ynerant**
While the installation is already super easy, using a Dockerfile and pushing Hydrogen to Docker hub could be even better :whale:

### CODE REVIEW

**Comment by bwindels** [comment]
Thanks for this. I'm fine with adding this file (we'll need DCO sign-off), but if I understand correctly, this would add a step to the release process of having to push to docker hub every time? I don't think I would want to do that at this point.

**Comment by ynerant** [comment]
Pushing to docker hub is not needed at this step of the project (but will be a good feature later when Hydrogen will be more stable ;-))
A Dockerfile only provides the steps to build a Docker image from the sources. This is useful if we want to have independant containers, without installing the application in our machine.

To build the image, simply run `docker build -t hydrogen .` (if . is the directory where the project is cloned), or better `docker build -t hydrogen https://github.com/vector-im/hydrogen-web.git`. Then, `docker run -p 3000:3000 hydrogen` launches the container and exposes the port 3000. We never installed yarn in our computer.

**Comment by bwindels** [comment]
Cool, can you just [sign off](https://github.com/matrix-org/matrix-js-sdk/blob/master/CONTRIBUTING.rst#sign-off) your commit?

**Comment by ynerant** [comment]
Better?

**Pull request merged**
