### PR TITLE
Docker Note

### PR DESCRIPTION
**Pull request by mcnesium**
Since I don't have yarn installed on my laptop, I ran this inside Docker. Thought I might share how I did this.

### CODE REVIEW

**Comment by bwindels** [comment]
I assume this overlaps with https://github.com/vector-im/hydrogen-web/pull/148?

**Comment by mcnesium** [comment]
Yes it does overlap. I guess I will update this PR once #148 is merged.

**Comment by bwindels** [comment]
It's merged now

**Comment by mcnesium** [comment]
…and I updated the readme

**Comment by febuiles** [comment]
I can't get the app running inside Docker by following the instructions, I'm using macOS 10.15.7 and Docker 19.03.13. On ff6ae86 I get:

```
$ docker run --name hydrogen-dev --publish 3000:3000 --volume "$PWD":/code --interactive --tty --rm hydrogen

yarn run v1.22.5
$ node scripts/serve-local.js
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'finalhandler'
Require stack:
- /code/scripts/serve-local.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/code/scripts/serve-local.js:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/code/scripts/serve-local.js' ]
}
error Command failed with exit code 1.
```

[Here](https://gist.github.com/febuiles/59a2d34a341ac0f1313982cd84920cdd) is the log of `docker build -t hydrogen .`

**Comment by bwindels** [comment]
So I've put the docker instructions in their own file with the caveat that they are not really supported, at least by me. I've linked to it in the main README. I feel this is more appropriate for the level of support I want to give running the local development in docker. So will close this PR, thank you for the instructions.

As far as your problem @febuiles, perhaps best to ask @mcnesium or ping the author of the docker file (@ynerant).

**Pull request closed without merging**
