### PR TITLE
Add room type in summary

### PR DESCRIPTION
**Pull request by ajbura**
Added room type and a method to get state event from indexedDB.

### CODE REVIEW

**Comment by robertlong** [comment]
Looks great 👍

**Comment by bwindels** [comment]
Didn't have time to review this before it got merged, but I would use `observeStateType`
& `observeStateTypeAndKey` on room instead of adding a getStateEvent method.

**Comment by robertlong** [comment]
Ah, I thought you had reviewed it based on the comments above. @ajbura can you make that change?

**Comment by ajbura** [comment]
@bwindels , `getStateEvent` is for different purpose. When we use `getStateEvent` we just want to read the current state (one time) without caring about the future changes to that state. Whereas `observeStateType` & `observeStateTypeAndKey` do care that we observe accessed state (subscribe it) for future changes. We do can use it to get the `stateObserver` and read the current state from it, but we need to subscribe it or else we will end up memory leak because [remove state observer from room function](https://github.com/vector-im/hydrogen-web/blob/thirdroom/dev/src/matrix/room/BaseRoom.js#L87,L89) will never get called.

**Comment by ajbura** [comment]
@robertlong , That was [diff](https://github.com/vector-im/hydrogen-web/pull/774) PR.

**Pull request merged**
